[workspace]
authors = ["Malte Busmann <m.busmann@physik.lmu.de>"]
channels = ["conda-forge", "fermi/label/main", "fermi", "threeml/label/dev" ]
name = "Fermi_Summer_School_2026"
platforms = ["linux-64", "osx-arm64",  "osx-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
notebook = "jupyter notebook --ip 00.00.00.00 --no-browser"
fshell = "pixi shell"

[tasks.notebook-fermi]
depends-on = [
  { task = "notebook", environment = "fermi" },
]

[tasks.fermi-env]
depends-on = [
  { task = "fshell", environment = "fermi" },
]

# [tasks.notebook-fermigbm]
# depends-on = [
#   { task = "notebook", environment = "fermigbm" },
# ]

[dependencies]
git = "*"
pipx = "*"
regions = "<0.12" # FermiPy needs .11, but we do work with .12
python = "3.12.*"
jupyter = "*"
jupyterlab = "*"
astropy = "<8.0.0"
pytest = "*"
junit-xml = "*"
ipyparallel = "*"
taplo = "*"
ipykernel = "*"
nbmake = "*" # 1.5.5
nb_conda_kernels = "*"
numpy = ">2.0"
xpa = "*"
xorg-libxt = "*"
xorg-libx11 = "*"          # Add this
xorg-libxext = "*"         # Add this
pgplot = "*"
healpy = "*"
libpng = "*"
matplotlib = "*"
scipy = "<1.18"
pytest-xdist = "*"
pmw = "*"
seaborn = "*"


# [pypi-dependencies]
#pyds9 = ">=1.8.1, <2"
astromodels = { git = "https://github.com", branch = "dev" }
fermipy
threeml = { git = "https://github.", branch = "dev" }

[feature.fermi.dependencies]
fermitools = "==2.5.3"
gammapy = ">=2.0"
fermipy = ">=1.4.3"


# [feature.fermigbm.dependencies]
# basemap = ">=2.0.0,<3"

# [feature.fermigbm.pypi-dependencies]
# gbm-data-tools = { path = "gbm_data_tools-1.1.1" }

[environments.fermi]
features = ["default", "fermi"]

# [environments.fermigbm]
# features = ["default", "fermigbm"]
