name: CI conda delete
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: anaconda/actions/setup-anaconda-cli@main
        id: setup-anaconda-cli
        with:
          version: latest
          tools: anaconda-cli

      - name: Show installed version
        run: |
          echo "Installed version: ${{ steps.setup-anaconda-cli.outputs.version }}"
          ana --version
          export PATH="$HOME/.local/bin:$PATH"
          ana login 
          # ana mcp setup
          # anaconda mcp terms accept
          # ana mcp discover
          # ana mcp get-metadata --package <package-name>
          # ana bootstrap
          # ana whoami
          anaconda whoami
          # anaconda show fermi/fermitools
